<?php

namespace Tests;

use Creational\Pool\Car;
use Creational\Pool\CarPool;
use PHPUnit\Framework\TestCase;

class PoolTest extends TestCase
{

    private CarPool $carPool;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
    }

    public function test_can_rent_car()
    {
        $myCar = $this->carPool->rentCar();
        $myCar2 = $this->carPool->rentCar();

        $this->assertInstanceOf(Car::class , $myCar);

        $this->assertEquals(1 , $this->carPool->getReport());
    }

    public function test_can_free_Car()
    {
        $myCar = $this->carPool->rentCar();

        $this->carPool->freeCar($myCar);
        $this->assertEquals(0 , $this->carPool->getReport());
    }

}